---
title: "Quantos Project"
output: html_notebook
---

```{r}
# Load libraries
library(tidyverse)
library(lubridate)
```

Read combined Quantos data. Rerun `read_quantos_files.R` to regenerate csv.

```{r}
quantos_data <- read_csv("data/quantos_data.csv")
```

Initial plot

```{r}
ggplot(quantos_data, aes(timestamp, mass, color = valid)) +
  geom_point() +
  geom_smooth()
```

Remove obvious outliers

```{r}
quantos_data %>%
  filter(mass < 50) %>% 
ggplot(aes(timestamp, mass, color = valid)) +
  geom_point() +
  geom_smooth()
```

We should probably reclass this by size, but for now, let's look at 2.5mg iron. Filtering by mass.

```{r}
q25 <- quantos_data %>% 
  filter(mass < 3,
         mass > 2.2)
```

```{r}
ggplot(q25, aes(timestamp, mass, color= valid))+
  geom_point()+
  geom_smooth()
```

Summarize valid 2.5mg data

```{r}
q25_good <- filter(q25, valid == "Valid")
summarize(q25, across(mass, list(mean = mean, sd = sd)))
```
Change in 2.5mg data over time

```{r}
q25_sum <- q25 %>% 
  group_by(month = floor_date(timestamp, "month")) %>%
  summarize(mass_mean = mean(mass),
            mass_sd = sd(mass))

ggplot(q25_sum, aes(month, mass_mean, ymin = mass_mean - mass_sd, ymax = mass_mean + mass_sd)) +
  geom_pointrange()
```

Histogram

```{r}
ggplot(q25_good, aes(mass))+geom_histogram()
```

